# SSL certificate generation:
#
# openssl genrsa -out webhook_pkey.pem 2048
# openssl req -new -x509 -days 3650 -key webhook_pkey.pem -out webhook_cert.pem
# When asked for "Common Name (e.g. server FQDN or YOUR name)" you should reply
# with the same value in you put in WEBHOOK_HOST

bot:
    # telegram API token here
    api_token: 111111333:AAF3LQKKFX16YDXlcqEGwCOUaa7rbFAwq9p

server:
    host: 91.31.21.21 # In some VPS you may need to put here the IP addr
    port: 8443 # 443, 80, 88 or 8443 (port should be accessible outside NAT)
    listen: 0.0.0.0 # server listen address
    ssl_cert: webhook_cert.pem  # Path to the ssl certificate
    ssl_key: webhook_pkey.pem # Path to the ssl private key
